const kReadingBingoChallenges = <String>[
  'One-word title',
  'Set abroad',
  "Friend's rec",
  'New author',
  '500+ pages',
  'Read in a day',
  'Historical',
  'Female author',
  'Series book',
  'Reread fave',
  'Debut novel',
  'FREE SPACE',
  'Classic lit',
  'Thriller',
  'Audiobook',
  'Own-voices',
  'Short stories',
  'DNF guilt-free',
  'Award winner',
  'Cover buy',
  'Adapted to film',
  'POC author',
  'Romance',
  'Non-fiction',
  'Finished series',
];
